### ISSUE TITLE
moar examples

### ISSUE THREAD

**Issue by valyagolev** [ai/evolu-lang#1]
any problem the language can solve

**Comment by ai** [comment]
Any Turing completeness tasks.

**Comment by ai** [comment]
Now it just a prototype of non-hierarchical language for genetic programming. I now try to find good examples to text language.

**Comment by valyagolev** [comment]
I don't mean "I want to know why is it useful". I just think that README will be improved by 420% if you show something cool :)

**Comment by ai** [comment]
Yeah, btw repo address is changed to https://github.com/evolu/evolu-lang

**Comment by ai** [comment]
I think about cool example, thanks.
